apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme
  namespace: acme
  labels:
    app: acme
    platform.io/tier: large
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acme
  template:
    metadata:
      labels:
        app: acme
    spec:
      containers:
        - name: acme
          image: acr.azurecr.io/acme/orders-api:latest
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          envFrom:
            - secretRef:
                name: acme-secrets
