apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acme-secrets
  namespace: acme
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kv-acme-prod-store
    kind: SecretStore
  target:
    name: acme-secrets
  dataFrom:
    - extract:
        key: acme
