apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: acme-base

commonLabels:
  app.kubernetes.io/part-of: acme
  platform.io/tenant: acme
  platform.io/tier: large

resources:
  - deployment.yaml
  - service.yaml
  - external-secret.yaml
