# Auto-generated by Copier for tenant: acme
# Component: app-gateway

resource "azurerm_application_gateway_listener" "acme" {
  name                  = "acme-listener"
  application_gateway_id = data.azurerm_application_gateway.shared.id

  frontend_ip_configuration_name = "shared-frontend-ip"
  frontend_port_name             = "https-443"
  protocol                        = "Https"
  host_name                       = "acme.platform.example.com"
}

resource "azurerm_application_gateway_backend_address_pool" "acme" {
  name                    = "acme-backend-pool"
  application_gateway_id  = data.azurerm_application_gateway.shared.id
  fqdns                   = ["acme-internal.svc.cluster.local"]
}

resource "azurerm_application_gateway_request_routing_rule" "acme" {
  name                       = "acme-routing-rule"
  application_gateway_id     = data.azurerm_application_gateway.shared.id
  rule_type                  = "Basic"
  http_listener_name         = azurerm_application_gateway_listener.acme.name
  backend_address_pool_name  = azurerm_application_gateway_backend_address_pool.acme.name
  priority                   = 100
}
