apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internalbatch-dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: internalbatch
    count: 1
images:
  - name: acr.azurecr.io/internalbatch/worker
    newTag: dev
